INSERT INTO USERS (ID, FULL_NAME, EMAIL, PASSWORD, CONFIRMED) VALUES (-1, 'admin', 'admin', STRINGDECODE('x61Ey612Kl2gpFL56FT9weDnpSo4AV8j8+qx2AuTHdRyY036xxzTTrw10Wq3+4qQyB+XURPWx1ON\nxp3Y3pB37A=='), true);
INSERT INTO USERS (ID, FULL_NAME, EMAIL, PASSWORD, CONFIRMED) VALUES (-2, 'user1', 'user1', STRINGDECODE('x61Ey612Kl2gpFL56FT9weDnpSo4AV8j8+qx2AuTHdRyY036xxzTTrw10Wq3+4qQyB+XURPWx1ON\nxp3Y3pB37A=='), true);
INSERT INTO ROLES (ID, NAME, DESCRIPTION) VALUES (-1, 'admin', 'admin');
INSERT INTO ROLES (ID, NAME, DESCRIPTION) VALUES (-2, 'user', 'user');
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (-1, -1);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (-1, -2);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (-2, -2);

INSERT INTO FAVORITES (ID, USER_ID, FAVORITE) VALUES (-1, -1, 'table');
INSERT INTO FAVORITES (ID, USER_ID, FAVORITE) VALUES (-2, -2, 'apple');
INSERT INTO FAVORITES (ID, USER_ID, FAVORITE) VALUES (-3, -2, 'car');
INSERT INTO FAVORITES (ID, USER_ID, FAVORITE) VALUES (-4, -2, 'door');

